***
**Name:** Khalid Saifullah \
**Student ID:** A20423546 \
**Course:** CS512 \
**Semester:** Spring, 2023
***

In [60]:
# Importing Libraries
import numpy as np

## Question A Solution

In [61]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([-1,1,3])

ans2a = np.linalg.norm(a)
ans2b = np.arccos(a[0]/ans2a)
ans3 = a/ans2a
ans5 = np.arccos(np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)))
ans10 = np.linalg.lstsq(np.column_stack([a, b]), c, rcond=None)[0]

print('1.', 2*a - b, '\n')
print("2. ||a|| = ", ans2a, '\n', "  Angle = ", ans2b, "radian", '\n')
print('3.', a/ans2a, '\n')
print('4.', 'cos(a1) = ',ans3.item(0), '\n', '  cos(a2) = ',ans3.item(1), '\n', '  cos(a3) = ',ans3.item(2), '\n')
print("5. Angle between a and b = ", ans5, "radian", '\n')
print("6. a.b = ", np.dot(a,b), '\n', "  b.a = ", np.dot(b,a), '\n',)
print("7. a.b = ", np.cos(ans5)*np.linalg.norm(a)*np.linalg.norm(b), '\n',)
print("8. Scalar projection of b onto a = ", np.linalg.norm(b)*np.cos(ans5), '\n',)
print('9. The cross product of two vectors is perpendicular to both of them.\n', \
         '  So, a vector perpendicular to a = ', np.cross(a,np.random.random(len(a))), '\n')
print("10. a x b = ", np.cross(a,b), '\n', "  b x a = ", np.cross(b,a), '\n',)
print("11. Vector Perpendicular to both a & b = ", np.cross(a,b), '\n')
print("12. Linear Dependence of c on [a ; b] is that c = ", round(ans10[0],1), 'a ', round(ans10[1],1), 'b\n')
print("13. (a.Transpose) b = ", np.dot(a,b), '\n', "   a (b.Transpose) = \n", np.outer(a,b), '\n')

1. [-2 -1  0] 

2. ||a|| =  3.7416573867739413 
   Angle =  1.3002465638163236 radian 

3. [0.26726124 0.53452248 0.80178373] 

4. cos(a1) =  0.2672612419124244 
   cos(a2) =  0.5345224838248488 
   cos(a3) =  0.8017837257372732 

5. Angle between a and b =  0.2257261285527342 radian 

6. a.b =  32 
   b.a =  32 

7. a.b =  32.0 

8. Scalar projection of b onto a =  8.55235974119758 

9. The cross product of two vectors is perpendicular to both of them.
   So, a vector perpendicular to a =  [-0.82475532 -0.20570401  0.41205445] 

10. a x b =  [-3  6 -3] 
   b x a =  [ 3 -6  3] 

11. Vector Perpendicular to both a & b =  [-3  6 -3] 

12. Linear Dependence of c on [a ; b] is that c =  3.0 a  -1.0 b

13. (a.Transpose) b =  32 
    a (b.Transpose) = 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]] 



## Question B Solution

In [62]:
A = np.array([[1,2,3],[4,-2,3],[0,5,-1]], dtype=np.float64)
B = np.array([[1,2,1],[2,1,-4],[3,-2,1]], dtype=np.float64)
C = np.array([[1,2,3],[4,5,6],[-1,1,3]], dtype=np.float64)

print('1.', 2*A - B, '\n')
print('2. AB = ', np.matmul(A,B), '\n\n BA = ', np.matmul(B,A), '\n')
print('3. (AB).Transpose = \n', np.matmul(A,B).T, '\n\n (B.Transpose)(A.Transpose) = \n', np.matmul(B.T,A.T), '\n')
print('4. |A| = ', round(np.linalg.det(A),2), 'and |C| = ', np.linalg.det(C), '\n')
print('5. For two vectors to be orthogonal, their dot product has to be equal to 0.\n', \
     'For matrix A, row1 (dot) row2 = ', np.dot(A[0,:],A[1,:]), '\n', \
     'row1 (dot) row3 = ', np.dot(A[0,:],A[2,:]), '\n', \
     'row2 (dot) row3 = ', np.dot(A[1,:],A[2,:]), '\n\n', \
     'For matrix B, row1 (dot) row2 = ', np.dot(B[0,:],B[1,:]), '\n', \
     'row1 (dot) row3 = ', np.dot(B[0,:],B[2,:]), '\n', \
     'row2 (dot) row3 = ', np.dot(B[1,:],B[2,:]), '\n\n', \
     'For matrix C, row1 (dot) row2 = ', np.dot(C[0,:],C[1,:]), '\n', \
     'row1 (dot) row3 = ', np.dot(C[0,:],C[2,:]), '\n', \
     'row2 (dot) row3 = ', np.dot(C[1,:],C[2,:]), '\n\n', \
     'Here, the rows of ONLY matrix B are orthogonal to each other.\n')
print('6. A^(-1) = \n', np.linalg.inv(A), '\n\nB^(-1) = \n', np.linalg.inv(B), '\n')

1. [[ 1.  2.  5.]
 [ 6. -5. 10.]
 [-3. 12. -3.]] 

2. AB =  [[ 14.  -2.  -4.]
 [  9.   0.  15.]
 [  7.   7. -21.]] 

 BA =  [[  9.   3.   8.]
 [  6. -18.  13.]
 [ -5.  15.   2.]] 

3. (AB).Transpose = 
 [[ 14.   9.   7.]
 [ -2.   0.   7.]
 [ -4.  15. -21.]] 

 (B.Transpose)(A.Transpose) = 
 [[ 14.   9.   7.]
 [ -2.   0.   7.]
 [ -4.  15. -21.]] 

4. |A| =  55.0 and |C| =  0.0 

5. For two vectors to be orthogonal, their dot product has to be equal to 0.
 For matrix A, row1 (dot) row2 =  9.0 
 row1 (dot) row3 =  7.0 
 row2 (dot) row3 =  -13.0 

 For matrix B, row1 (dot) row2 =  0.0 
 row1 (dot) row3 =  0.0 
 row2 (dot) row3 =  0.0 

 For matrix C, row1 (dot) row2 =  32.0 
 row1 (dot) row3 =  10.0 
 row2 (dot) row3 =  19.0 

 Here, the rows of ONLY matrix B are orthogonal to each other.

6. A^(-1) = 
 [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]] 

B^(-1) = 
 [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04

## Question C Solution

In [64]:
D = np.array([[1,2],[3,2]], dtype=np.float64)
E = np.array([[2,-2],[-2,5]], dtype=np.float64)
F = np.array([[1,2],[2,4]], dtype=np.float64)

ans1 = np.linalg.eig(D)
ans3 = np.linalg.eig(E)

print('1. Eigen values of D = ', ans1[0], '\nAnd Corresponding normalized unit Eigen vectors = ', \
      ans1[1][0], 'and ', ans1[1][1],'\n')
print('2. Dot product between Eigen vectors of D = ', ans1[1][0].dot(ans1[1][1]), '\n')
print('3. Dot product between Eigen vectors of E = ', ans3[1][0].dot(ans3[1][1]), '\n')


1. Eigen values of D =  [-1.  4.] 
And Corresponding normalized unit Eigen vectors =  [-0.70710678 -0.5547002 ] and  [ 0.70710678 -0.83205029] 

2. Dot product between Eigen vectors of D =  -0.038461538461538214 

3. Dot product between Eigen vectors of E =  0.0 

